<?php

$this->sections[] = array(
	'icon' => 'dashicons dashicons-editor-paragraph',
	'title' => esc_html__( 'Typography', 'kraft' ),
	'heading' => '',
	'fields' => array(
		array(
			'id'   => 'info_typography_font_family',
			'type' => 'info',
			'desc' => esc_html__( 'Font family', 'kraft' )
		),
		array(
			'id' => 'body-font',
			'type' => 'typography',
			'title' => esc_html__( 'Font family', 'kraft' ),
			'google' => true,
			'font-family' => true,
			'font-weight' => false,
			'font-size' => false,
			'font-style' => false,			
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,		
			'subsets' => false,
			'all_styles' => false,
			'preview' => false,
			'color' => false,	
			'units' => 'px',
			'default' => array(				
				'font-family' => 'Roboto',								
			),
		),
		array(
			'id'       => 'body-font-style',
			'type'     => 'typography_font_style',
			'title'    => esc_html__( 'Font style', 'kraft' ), 
			'default'  => array(
							'100' => '0',
							'300' => '0',
							'400' => '1',
							'500' => '1',
							'700' => '1',								 
							'900' => '0',
							'100italic' => '0',
							'300italic' => '0',
							'400italic' => '0',
							'500italic' => '0',
							'700italic' => '0',								
							'900italic' => '0'					
						),			
			'desc'     => esc_html__( 'Choose the font style to load with font to lower load time.', 'kraft' ),
		),	
		array(
			'id' => 'heading-font',
			'type' => 'typography',
			'title' => esc_html__( 'Heading font family', 'kraft' ),
			'google' => true,
			'font-family' => true,
			'font-weight' => false,
			'font-size' => false,
			'font-style' => false,			
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,		
			'subsets' => false,
			'all_styles' => false,
			'preview' => false,
			'color' => false,		
			'units' => 'px',
			'default' => array(				
				'font-family' => 'Roboto',								
			),
		),
		array(
			'id'       => 'heading-font-style',
			'type'     => 'typography_font_style',
			'title'    => esc_html__( 'Heading font style', 'kraft' ), 
			'default'  => array(
							'100' => '0',
							'300' => '0',
							'400' => '1',
							'500' => '1',
							'700' => '1',								 
							'900' => '0',
							'100italic' => '0',
							'300italic' => '0',
							'400italic' => '0',
							'500italic' => '0',
							'700italic' => '0',								
							'900italic' => '0'				
						),			
			'desc'     => esc_html__( 'Choose the font style to load with heading font to lower load time.', 'kraft' ),
		),		
		array(
			'id'   => 'info_typography_font_sizes',
			'type' => 'info',
			'desc' => esc_html__( 'Font sizes', 'kraft' )
		),
		array(
			'id' => 'h1-font',
			'type' => 'typography',
			'title' => esc_html__( 'h1', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,						
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 				
				'font-size' => '44px',
				'font-weight' => '500',		
			),
		),
		array(
			'id' => 'h2-font',
			'type' => 'typography',
			'title' => esc_html__( 'h2', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 						
				'font-size' => '38px',	
				'font-weight' => '500',						
			),
		),
		array(
			'id' => 'h3-font',
			'type' => 'typography',
			'title' => esc_html__( 'h3', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,	
			'preview' => false,	
			'all_styles' => true,
			'google'  => true, 	
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 				
				'font-size' => '32px',		
				'font-weight' => '500',					
			),
		),
		array(
			'id' => 'h4-font',
			'type' => 'typography',
			'title' => esc_html__( 'h4', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,	
			'preview' => false,		
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 				
				'font-size' => '26px',	
				'font-weight' => '500',			
			),
		),
		array(
			'id' => 'h5-font',
			'type' => 'typography',
			'title' => esc_html__( 'h5', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,	
			'preview' => false,	
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(	
				'font-family' => 'Roboto', 						
				'font-size' => '22px',		
				'font-weight' => '500',					
			),
		),
		array(
			'id' => 'h6-font',
			'type' => 'typography',
			'title' => esc_html__( 'h6', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,	
			'preview' => false,		
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 			
				'font-size' => '20px',		
				'font-weight' => '500',					
			),
		),
		array(
			'id' => 'p-font',
			'type' => 'typography',
			'title' => esc_html__( 'p', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'subsets' => false,
			'color' => false,
			'letter-spacing' => false,
			'line-height' => false,		
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 					
				'font-size' => '15px',			
				'font-weight' => '400',						
			),
		),	
		array(
			'id'   => 'info_portfolio_typography',
			'type' => 'info',
			'desc' => esc_html__( 'Portfolio Typography', 'kraft' )
		),	
		array(
			'id' => 'portfolio-primary-title',
			'type' => 'typography',
			'title' => esc_html__( 'Primary Title', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => true,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(
				'font-family' => 'Roboto', 							
				'font-size' => '38px',
				'line-height' => '44px',
				'font-weight' => '500',		
			),
		),
		array(
			'id' => 'portfolio-secondary-title',
			'type' => 'typography',
			'title' => esc_html__( 'Secondary Title', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(
				'font-family' => 'Roboto', 							
				'font-size' => '32px',			
				'font-weight' => '500',		
			),
		),
		array(
			'id' => 'portfolio-meta-button',
			'type' => 'typography',
			'title' => esc_html__( 'Meta Button', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => true,
			'text-transform' => true,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 				
				'font-size' => '12px',			
				'font-weight' => '500',		
				'text-transform' => 'uppercase',
				'letter-spacing' => '1px'
			),
		),
		array(
			'id'             => 'portfolio-meta-button-padding',
			'type'           => 'spacing',		
			'mode'           => 'padding',
			'units'          => array( 'px' ),
			'units_extended' => 'false',
			'title'          => esc_html__( 'Meta Button Padding', 'kraft' ),
			'subtitle'       => esc_html__( 'Padding top/right/bottom/left (px).', 'kraft' ),			
			'default'        => array(
									'padding-top'     => '12px', 
									'padding-right'   => '24px', 
									'padding-bottom'  => '12px', 
									'padding-left'    => '24px',
									'units'          => 'px', 
								)
		),
		array(
			'id'   => 'info_blog_typography',
			'type' => 'info',
			'desc' => esc_html__( 'Blog Typography', 'kraft' )
		),
		array(
			'id' => 'blog-banner-title',
			'type' => 'typography',
			'title' => esc_html__( 'Banner Title', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(	
				'font-family' => 'Roboto', 					
				'font-size' => '60px',				
				'font-weight' => '500',		
			),
		),	
		array(
			'id' => 'blog-post-title',
			'type' => 'typography',
			'title' => esc_html__( 'Post Title', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(	
				'font-family' => 'Roboto', 						
				'font-size' => '36px',				
				'font-weight' => '500',		
			),
		),	
		array(
			'id' => 'blog-comment-title',
			'type' => 'typography',
			'title' => esc_html__( 'Comment/Reply Title', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 					
				'font-size' => '34px',				
				'font-weight' => '500',		
			),
		),	
		array(
			'id' => 'blog-widget-title',
			'type' => 'typography',
			'title' => esc_html__( 'Widget Title', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => false,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(	
				'font-family' => 'Roboto', 					
				'font-size' => '28px',				
				'font-weight' => '500',		
			),
		),	
		array(
			'id' => 'blog-post-button',
			'type' => 'typography',
			'title' => esc_html__( 'Post Button', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => true,
			'text-transform' => true,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(			
				'font-family' => 'Roboto', 			
				'font-size' => '12px',			
				'font-weight' => '500',		
				'text-transform' => 'uppercase',
				'letter-spacing' => '.5px'
			),
		),
		array(
			'id'             => 'blog-post-button-padding',
			'type'           => 'spacing',		
			'mode'           => 'padding',
			'units'          => array( 'px' ),
			'units_extended' => 'false',
			'title'          => esc_html__( 'Post Button Padding', 'kraft' ),
			'subtitle'       => esc_html__( 'Padding top/right/bottom/left (px).', 'kraft' ),			
			'default'        => array(
									'padding-top'     => '9px', 
									'padding-right'   => '18px', 
									'padding-bottom'  => '9px', 
									'padding-left'    => '18px',
									'units'          => 'px', 
								)
		),
		array(
			'id'   => 'info_typography_button',
			'type' => 'info',
			'desc' => esc_html__( 'Button', 'kraft' )
		),
		array(
			'id' => 'general-button',
			'type' => 'typography',
			'title' => esc_html__( 'Button', 'kraft' ),
			'font-family' => true,
			'font-weight' => true,
			'font-style' => true,
			'text-align' => false,
			'line-height' => false,
			'letter-spacing' => true,
			'text-transform' => true,
			'subsets' => false,
			'color' => false,			
			'preview' => false,
			'all_styles' => true,
			'google'  => true, 
			'units' => 'px',
			'default' => array(		
				'font-family' => 'Roboto', 					
				'font-size' => '13px',			
				'font-weight' => '500',		
				'text-transform' => 'uppercase',
				'letter-spacing' => '1px'
			),
		),
		array(
			'id'             => 'general-button-padding',
			'type'           => 'spacing',		
			'mode'           => 'padding',
			'units'          => array( 'px' ),
			'units_extended' => 'false',
			'title'          => esc_html__( 'Button Padding', 'kraft' ),
			'subtitle'       => esc_html__( 'Padding top/right/bottom/left (px).', 'kraft' ),			
			'default'        => array(
									'padding-top'     => '14px', 
									'padding-right'   => '28px', 
									'padding-bottom'  => '14px', 
									'padding-left'    => '28px',
									'units'          => 'px', 
								)
		),
		array(
			'id'   => 'info_typography_colors',
			'type' => 'info',
			'desc' => esc_html__( 'Colors', 'kraft' )
		),
		array(
			'id' => 'heading-color',
			'type' => 'color',
			'title' => esc_html__( 'Heading color', 'kraft' ),
			'subtitle' => esc_html__( 'Choose the heading font color from here.', 'kraft' ),			
			'transparent' => false,
			'default'   => '#151515'
		),		
		array(
			'id' => 'body-color',
			'type' => 'color',
			'title' => esc_html__( 'Body color', 'kraft' ),
			'subtitle' => esc_html__( 'Choose the body font color from here.', 'kraft' ),			
			'transparent' => false,
			'default'   => '#707070'
		),		
	)
); 